dist: xenial
language: python
cache: pip
python:
  - "3.7.3"
install:
  - pip install pipenv --upgrade
  - pipenv sync -d
script:
  - black --check -l79 docker_cp/ tests/
  - pytest -vv -x --cov-report term-missing --cov=.
after_success:
  - codecov
